### ISSUE TITLE
Raspberry Pi 5 support

### ISSUE THREAD

**Issue by matthiasklein** [rauc/meta-rauc-community#79] opened 2024-01-26 11:34 UTC
Is anyone working on support for the Raspberry Pi 5?

Yocto support exists in the meantime. But no U-Boot.
A good summary can be found here in the Mender forum: https://hub.mender.io/t/raspberry-pi-5-support/6412

I think it would be interesting to do without U-Boot altogether and use the "tryboot" feature instead, which exists since the Raspberry Pi 4.

**Comment by leon-anavi** [comment] 2024-01-26 11:45
Hi @matthiasklein,

Yes, it is kind of work in progress:

* Yesterday the GitHub pull request for Raspberry Pi 5 support was merged in meta-raspberrypi: https://github.com/agherzan/meta-raspberrypi/pull/1237

* Today I opened a GitHub pull request to port Raspberry Pi 5 from the main branch to kirkstone: https://github.com/agherzan/meta-raspberrypi/pull/1271

* Previously I got mender working on Raspberry Pi 5 using unstable U-Boot patches from the mailing lists that haven't been merged in U-Boot yet. The process for RAUC integration is similar. So it is a work in progress and it depends on the other 2 GitHub pull requests mentioned above.

Best regards,
Leon

**Comment by m4salem** [comment] 2024-02-15 18:14
Thanks for the work on this, I was wonderinf if this issue is still being considered

**Comment by leon-anavi** [comment] 2024-02-15 18:26
> Thanks for the work on this, I was wondering if this issue is still being considered

Yes, in general but it is not on top of my priority list. Actually the mentioned GitHub pull request to port Raspberry Pi 5 from the main branch to branch kirkstone in meta-raspberrypi was merged: https://github.com/agherzan/meta-raspberrypi/pull/1271

**Comment by m4salem** [comment] 2024-02-15 20:40
Yeah I have been following those, and the RPI5 works fine. The problem now is that RAUC can't be built for RPI5.

**Comment by leon-anavi** [comment] 2024-02-15 20:43
> Yeah I have been following those, and the RPI5 works fine. The problem now is that RAUC can't be built for RPI5.

Yes, because RAUC integration in meta-rauc-raspberrypi relies on U-Boot and as I mentioned in the previous comments the U-Boot support for rpi5 is still work in progress.

**Comment by moto-timo** [comment] 2024-03-29 16:20
I have working branches which will be submitted as soon as the [meta-lts-mixins](https://git.yoctoproject.org/meta-lts-mixins) `scarthgap/u-boot` branch is created. But for now you can play around and give me feedback (good or bad). I have had a little bit of issue with needing the `UART` probe installed to get `u-boot` to boot completely, and also some framebuffer transition issues (the four raspberrypi logos for the 4 cores stay on screen). Your mileage may vary.

1. https://github.com/moto-timo/meta-lts-mixins/tree/scarthgap/u-boot
2. https://github.com/moto-timo/meta-raspberrypi/tree/scarthgap/raspberrypi5_u-boot
3. https://github.com/moto-timo/meta-rauc-community/tree/scarthgap/raspberrypi5_u-boot

**Comment by moto-timo** [comment] 2024-03-29 16:26
Any feedback is helpful. Even if it is "this doesn't work at all and here is what I saw". Reproducers for failures (or fixes) are much appreciated.

**Comment by moto-timo** [comment] 2024-03-29 16:28
FWIW, I had zero issue with `yoe-simple-image` https://github.com/YoeDistro/yoe-distro/pull/912 but that is not using `u-boot` at all.

**Comment by leon-anavi** [comment] 2024-06-13 11:27
Hi,

Recently @AtanasBunchev tested Poky with Raspberry Pi 5 based on @moto-timo work. Atanas updated the README with details: https://github.com/rauc/meta-rauc-community/pull/100

RAUC is now compatible with the Raspberry Pi 5, so I will be closing this issue. A huge thanks to Tim for his work on U-Boot and to everyone who contributed to this task.

Best regards, Leon

**Closed by leon-anavi** 2024-06-13 11:27 UTC
